### ISSUE TITLE
Still getting more windows

### ISSUE THREAD

**Issue by rdailey** [VanCoding/One-Window#2]
I used to use this extension and trying to open new windows would merge the new window into the existing window on a new tab.  Now I get new windows even though One Window is installed and enabled.  It is version 3.0.0, and I have tried it on more than one computer with the same results.

**Comment by VanCoding** [comment]
I've this option for you.
To enable it go to the extensions tab in chrome settings, enable developer mode, click the background page of one-window, go to the console tab, enter the following:

```
localStorage["all"] = true;
```

Press enter, and that's it ;)
