### ISSUE TITLE
Please let the new tabs open just right to its parent tab instead of all the way to the right 

### ISSUE THREAD

**Issue by tarekatgh** [VanCoding/One-Window#7]
First of all, I want to thank you for creating such a beautiful extension.

However, there is one little feature of this extension which I'd prefer changed. When a link (let's call it link L) on, say tab A, is clicked on to open in a new tab N, BUT another tab, say tab B, was right to the tab A already BEFORE clicking on that link L, the new tab N opens ALL THE WAY to the right (which is right to the tab B) instead of immediately right to the tab A (which is more logical, since the the link L should be opened in a tab immediately right to the tab where it was found.)

Many other users of this extension on the Chrome Web Store have reported the same issue, so I hope this will really get your kind attention.

Thank you very much once again.

**Comment by VanCoding** [comment]
Implementing it the way you wish would require  that the extension knows which tab was responsible for the creation of the new window.

I'm not sure yet if this is the case and thus have to check that first before I can tell you if I'll do it or not.

**Comment by VanCoding** [comment]
Ok after looking at the chrome API Reference I can tell know that I don't have the information about which tab created the new window. What I do know, however, is which tab is currently active, so I could always move converted tabs to the right of that. Would that be acceptable?

**Comment by tarekatgh** [comment]
Sorry for the late reply. Yes, that should do it nicely. Thank you very much for your response.

**Comment by tarekatgh** [comment]
Sorry for the late reply. Yes, that should do it nicely. Thank you very
much for your response.

**Comment by VanCoding** [comment]
I've now implemented this!
Can you maybe download the new zip from github and check if if you find any bugs before I publish it to the chrome web store?

To me it seems ok.

Thank you!

**Comment by tarekatgh** [comment]
Sorry for late reply again. I had exams, so I couldn't reply earlier. 

Yes, I have checked it. And yes, it seems all right so far. I will let you know if I find any bugs, though. 

Thank you very much for your response and great help.

**Comment by VanCoding** [comment]
Landed in 3.0.2

**Comment by VanCoding** [comment]
I had to remove that feature again in 3.0.6, since this feature lead to serious problem with the whole one window functionality as reported in #8. Since I, even after long work, could not made it work, and people have seen tabs not opening to the very right of the window as a bug, I decided to move back.

I'm sorry about that.
